server.port=8089

spring.web.cors.allowed-origin-patterns=*
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

spring.data.mongodb.uri=mongodb://127.0.0.1:27017/recruitai
spring.data.mongodb.database=recruitai
# de.flapdoodle.mongodb.embedded.version=5.0.5
spring.application.name=recruitai-agent
logging.level.com.recruitai.agent=DEBUG
logging.file.name=backend.log
spring.data.mongodb.auto-index-creation=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ✅ Gemini Config (Using 1.5 Pro for stability)
gemini.api.key=AIzaSyAgw-R2WOl51gW61Qz8xfWPM0MGf7dHY8M
gemini.api.model=gemini-2.0-flash-001

# ----------------- EMAIL CONFIGURATION -----------------
# Uncomment and fill in your SMTP details to enable email sending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aparnaboligerla@gmail.com
spring.mail.password=ldzcttvpqzugxjxi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# ----------------- ZOOM API CONFIGURATION -----------------
zoom.account.id=HLXgXWy3Q3KNATmYpSGJsg
zoom.client.id=C6rMZiuKRQ5rcGNLplhnw
zoom.client.secret=86L7E14Cc13Y5jNf925NAhUGsY52g29P
zoom.api.base-url=https://api.zoom.us/v2
zoom.oauth.url=https://zoom.us/oauth/token
